name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VERSION: 0.9.${{github.run_number}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore /p:Version=$VERSION
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal /p:Version=$VERSION
    - name: Package
      run: dotnet pack -c Release --no-build /p:Version=$VERSION -o ./PackagesOut
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: CsgPackages
        path: ./PackagesOut/*.nupkg
